{% set version = '0.1-2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sroc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sROC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sROC/sROC_{{ version }}.tar.gz
  sha256: a3815fbf0c78d9f03ff2c456f0573347d12cbf43173752c872aed9346176e632

build:
  number: 1007
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [unix]
    - {{ stdlib("c") }}          # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('sROC')"  # [not win]
    - "\"%R%\" -e \"library('sROC')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=sROC
  license: GPL-3.0-or-later
  summary: This package contains a collection of functions to perform nonparametric estimation
    of receiver operating characteristic (ROC) curves for continuous data.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
