travis:
  secure:
    BINSTAR_TOKEN: UTYncf535kjguFJxYw+sAwyx9Vuw8/bzV/foYOuz+LobYskutvetlegoJd/L0DLFgM++2QfxJlysmRH8jGCsZtW+vXjhMIiqPUWP4bqMYcYHrPXFCbyc1uWDX9HlbR8tQY7cAKW9A5F2eLWFm2rWC0FNFP3QJL3tOrT2lIhSKD11lIYgOZX8KAMUucVfpox+AxoonuOB0qGsLYGsgi8rADDDsL20Z2RNEBO+8MLfxTn6j+JkMapeIyOncQJwdw8gso2H0IXWtahRfVaQFUj82CxfaUYUBI2Gjfd1/YRkDe8czobHqmiCo2k0pb+vyVRit1FWKxEPOr/z9BBeIDdt0mXSX1S6bO4cYTQNTro56InpsZrhGwFT5ckKozPIdBhqD5NvCCd6IXfPJkhz8nZdncUYHWBgXKnq1oSqHDEiYMAHP8cS9rvmFuW0NVBzRkQatlwfQb0asQsNS365h9vxnQc6H77BLgAIyT6HquedBaALW+BEtk97QsSbB7LlZ7CqjacJKgF2ehxkg2aECaXkMBjR7KgYebhsXvDQ655ostK4eOAszxEvZr7uGR2JWwRpZkKdb2dQ+cPMo22XsBmrmH1JjjoO/yrZnNgvl08iNPq/n85tPlyTGedGJo3SyOoLh2c5Q6aOf5QsYdEI/57FeW9qPdfhG/3L1IfB6DTbiJw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
