travis:
  secure:
    BINSTAR_TOKEN: E1GtE6Z0jF31rDx0diAiOgxaVkBv4TrHMX1DdNY16J46ZNg76yVrxqXk9GbcroPAKD58ofLv0QqSc6O8ZLCBJHB4s8eoEX7lb+Xt+/kzr9Fd7CGOEOy/gP7yUBW6tZRVmham7j+GZhGuKPu+jN+v0JFq+y69r10AtjeYTWtbaHLoMkkpmuGBxR/pqQJLobyMO+Yd/0oHXrPjh7WW6sqQmCgLDAt4JkifA39Ket5RJRjpijoJokUbvimYB2bnNKKo51LxfwXSZsLpj9afNN4Fs/22XJR4Pqh5VWmfSi8Ws2pgeiLrGKxQI7pFST88tgl9DPMvWEFp/wJQ4Uub+GwNiesjGP/eh2ZQFu05c7bcJoTNdoYaFE2y3h7Igg38Y0Acppzh45SqQLIOMybqaWWBvOAxKGwVW0PnlXLY6b0/hIVlmyKd+GJZshhBkDzX32ngnFdbjTc7xiIgaodiNSKg5DPbrdFuzRy5/2MMsDzNdeOkS2xCNbtvHmINyvfL/IpzuIYioqheJTXS/xsNsQJFn7E67++KjdiJV2oYMwhY4pqU5LaN8mBR367YYNQgqQumjnnhiNtNQwhHS8MEtV5vu+yrllHDIz5A0G1nQHiP5OuAqZE+imfodcHpFi5wipxpTjazVZz3K+nciJNV18ZShHS5l8pa4LuvpzlZ4n05Vck=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
