travis:
  secure:
    BINSTAR_TOKEN: ROnNSWcS03d8Bs2rBmqhZH41V7FtWPsz0HhSzrw/TG7NtYMQo0vAecfb/ewoXjsX8jMpfJnN2abXfzB7BD3mGpAGWT3SXnJ8Q+UDmXIWo+yMQQe+4A7ChqPChukdghLDOW8JbxP+RovzpeLNymSsn95BHtDeBcjyWTHWzgCoDgLjSN3bbIrLjqLZ8wLzUROe7xfRUvi3GXZrgkaKY+NGUzY0Iyh5vF9lpO2obpZgKUKRD6P+uFKQHhhFynY6Qy1X4HikxIJvx6ZRVwLmTF6tdYHFdqOINas335omk2i4tZwAGxSuLeItDzPtv3s3W6URNkrac/G11sd8W4lg4hkyHnV0tODn4t6/B+GqHTLNWuwZlXJ62kGFNGWvC5vLh6LbnQfISdtrSLZSsBOvYY9zQFq/kWiSSxJRv6L00XtDBAm4SHKAlPm4hiatMsYrCooJsq53Lb8IdcYofOPHxYj2HF8XdH5m4vEiyrUZ++jDKQWeCxcY4DZuVQL6ZzSgCHsm/En+Tp/vDMp3V9ImRxJVe+MGOdDXR5DwNjGxKyssTsZYVhqFn31y7pd9hjc4S34cAjGsml32I5GSYxwbGh9QFFKIqer59FqQa0v799lBoD4unfJvyax/y8iqVqVJYXkPBpd/m4R80Hf+K9oIG8CFAmZySo/+ZIVUGviClJrCW8E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
